function Distance = gtrack_calcDistance(p1,p2)
    Distance = p1.range*p1.range + p2.range*p2.range - ...
        2*p1.range*p2.range*...
        (cos(p1.elevation)*cos(p2.elevation)*cos(p1.azimuth-p2.azimuth)+sin(p1.elevation)*sin(p2.elevation));
end